// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PKM_Audio","status":true,"description":"[PKM v0.5] Áudio: cries dos Pokémon, BGM de batalha e fanfarra de\nvitória. Integra-se à batalha automaticamente (opcional).","parameters":{"cryFolder":"Cries/","crySuffix":"Cry","wildBgm":"Battle1","trainerBgm":"Battle2","victoryWildMe":"Victory1","victoryTrainerMe":"Victory2"}},
{"name":"PKM_Bag","status":true,"description":"[PKM v0.3] Mochila por bolsos, dinheiro, efeitos de itens (cura/PP/\nrevive/status) e cena da mochila. Integra Poké Bolas com a batalha.","parameters":{}},
{"name":"PKM_Battle","status":true,"description":"[PKM v0.2] Batalha selvagem 1v1: turnos, dano por tipo/STAB/crítico,\ntroca, fuga e CAPTURA (Poké Ball). Fórmulas puras em PKM.Battle.","parameters":{}},
{"name":"PKM_Core","status":true,"description":"[PKM v0.1] Núcleo do port do Pokémon Essentials para MZ. Carrega os\ndados das espécies e controla o estado da Pokédex (vistos/capturados).","parameters":{}},
{"name":"PKM_Encounters","status":true,"description":"[PKM v0.2] Encontros selvagens no overworld a partir de Encounters.json.","parameters":{"grassRegionId":"1","stepDivisor":"250"}},
{"name":"PKM_Party","status":true,"description":"[PKM v0.2] Party de até 6 Pokémon + telas de equipe e resumo.","parameters":{}},
{"name":"PKM_Pokedex","status":true,"description":"[PKM v0.1] Sistema de Pokédex: lista navegável + ficha de detalhes\n(tipos, categoria, altura/peso, descrição), com estado visto/capturado.","parameters":{}},
{"name":"PKM_Pokemon","status":true,"description":"[PKM v0.2] Modelo do Pokémon individual (Game_Pokemon): natureza,\nIVs/EVs, stats calculados, golpes, gênero, HP/status. Base de party e batalha.","parameters":{}},
{"name":"PKM_Storage","status":true,"description":"[PKM v0.4] Sistema de PC: 16 caixas × 30 espaços, com depositar,\nretirar, mover/trocar e soltar Pokémon. Cena Scene_PkmStorage.","parameters":{}},
{"name":"PKM_Trainers","status":true,"description":"[PKM v0.4] Batalhas de treinador (equipes múltiplas, recompensa em\ndinheiro, sem captura/fuga) e insígnias de ginásio.","parameters":{}}
];
