// Generated by RPG Maker.
// Do not edit this file directly.
// Ordem por DEPENDENCIA (nao alfabetica): aliases e hooks exigem que o plugin
// alvo ja tenha rodado. MON_Parts depende de MON_Battle (hook de vitoria).
var $plugins =
[
{"name":"MON_Core","status":true,"description":"[MON v0.1] Núcleo do port do Pokémon Essentials para MZ. Carrega os\ndados das espécies e controla o estado da Pokédex (vistos/capturados).","parameters":{}},
{"name":"MON_Franchise","status":true,"description":"[MON v0.3] Camada multi-franquia: registro de dimensões, merge dos\ndados extras (espécies, golpes, itens) e regras de captura por franquia.","parameters":{}},
{"name":"MON_Monster","status":true,"description":"[MON v0.2] Modelo do Pokémon individual (Game_Monster): natureza,\nIVs/EVs, stats calculados, golpes, gênero, HP/status. Base de party e batalha.","parameters":{}},
{"name":"MON_Evolution","status":true,"description":"[MON v0.3] Evolução ramificada com condição (digievolução) e Digimemória.","parameters":{}},
{"name":"MON_Human","status":true,"description":"[MON v0.5] Humanos em campo: Game_Human luta lado a lado com os monstros.","parameters":{}},
{"name":"MON_Field","status":true,"description":"[MON v0.5] Campo de batalha em times (até 3v3): posições, ordem de turno, alvos e substituição.","parameters":{}},
{"name":"MON_Party","status":true,"description":"[MON v0.2] Party de até 6 Pokémon + telas de equipe e resumo.","parameters":{}},
{"name":"MON_Encounters","status":true,"description":"[MON v0.2] Encontros selvagens no overworld a partir de Encounters.json.","parameters":{"grassRegionId":"1","stepDivisor":"250"}},
{"name":"MON_Battle","status":true,"description":"[MON v0.2] Batalha selvagem 1v1: turnos, dano por tipo/STAB/crítico,\ntroca, fuga e CAPTURA (Poké Ball). Fórmulas puras em MON.Battle.","parameters":{}},
{"name":"MON_Bag","status":true,"description":"[MON v0.3] Mochila por bolsos, dinheiro, efeitos de itens (cura/PP/\nrevive/status) e cena da mochila. Integra Poké Bolas com a batalha.","parameters":{}},
{"name":"MON_Trainers","status":true,"description":"[MON v0.4] Batalhas de treinador (equipes múltiplas, recompensa em\ndinheiro, sem captura/fuga) e insígnias de ginásio.","parameters":{}},
{"name":"MON_Storage","status":true,"description":"[MON v0.4] Sistema de PC: 16 caixas × 30 espaços, com depositar,\nretirar, mover/trocar e soltar Pokémon. Cena Scene_PkmStorage.","parameters":{}},
{"name":"MON_Parts","status":true,"description":"[MON v0.3] Medabots: medalha + 4 slots de peças trocáveis e drop de peça pós-vitória.","parameters":{}},
{"name":"MON_Sanctuary","status":true,"description":"[MON v0.3] Monster Rancher: Santuário de Discos e treino de fazenda.","parameters":{}},
{"name":"MON_Pacts","status":true,"description":"[MON v0.3] Bucky: emblemas de Grande Criança e pacto com os 12 espíritos.","parameters":{}},
{"name":"MON_Dex","status":true,"description":"[MON v0.4] Dex regional por dimensão: recorte ordenado de espécies,\nnúmero regional, forma de obtenção e progresso de vistos/capturados.","parameters":{}},
{"name":"MON_Codex","status":true,"description":"[MON v0.1] Sistema de Pokédex: lista navegável + ficha de detalhes\n(tipos, categoria, altura/peso, descrição), com estado visto/capturado.","parameters":{}},
{"name":"MON_Audio","status":true,"description":"[MON v0.5] Áudio: cries dos Pokémon, BGM de batalha e fanfarra de\nvitória. Integra-se à batalha automaticamente (opcional).","parameters":{"cryFolder":"Cries/","crySuffix":"Cry","wildBgm":"Battle1","trainerBgm":"Battle2","victoryWildMe":"Victory1","victoryTrainerMe":"Victory2"}}
];
